# Generated by Django 5.1.5 on 2025-03-29 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0002_expensesplit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesplit',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
