# Generated by Django 5.1.5 on 2025-03-29 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0003_alter_expensesplit_amount_owed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesplit',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expensesplit',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.expense'),
        ),
        migrations.AlterField(
            model_name='expensesplit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
