# Generated by Django 5.1.5 on 2025-04-02 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0006_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesplit',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
