# Generated by Django 5.1.5 on 2025-04-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0007_expensesplit_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesplit',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='expensesplit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='payer',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='ExpenseSplit',
        ),
        migrations.DeleteModel(
            name='Settlement',
        ),
    ]
